update:
  check:
    enable: true
mysql:
  # 是否启用数据库存储
  # 如果启用，则需要安装MXBukkitLib插件
  # Нужно ли включить хранилище базы данных? 
  # Если нужно, тогда вам нужно установить плагин MXBukkitLib
  enable: false
  # 数据库链接
  # Ссылка на базу данных
  url: 'jdbc:mysql://localhost:3306/数据库名?useSSL=false'
  # 存储数据表名
  # Имя таблицы данных хранилища
  tableName: 'imipetsql'
  # 数据库用户名
  # Имя пользователя базы данных
  user: 'user'
  # 数据库密码
  # Пароль базы данных
  password: 'password'

# 禁用宠物跟随状态的世界
# Отключить мир для петов
disablePetWorld:
  - secc_world
  - uopworld

# 关于宠物显示名与名称设置
# О настройке отображаемого имени пета
petName:
  # 更名上限字符
  # Переименовать Cap Cap Character
  maximum: 6
  # 更名禁用的字符
  # Переименовать запрещенные символы
  disableWords:
    - "&"
    - "%"
    - "sb"
    - "垃"
  # 更名所需经济
  # Экономика нужна для смены имени
  money:
    # 是否启用
    # Включить?
    enable: true
    # 需要多少经济
    # Какая цена?
    need: 100
# 关于强制回收宠物
# О принудительной утилизации домашних животных
takeBack:
  # 是否开启在几秒后重新召唤宠物
  # Включить возобновление домашних животных через несколько секунд?
  enable: false
  # 秒
  # Через какое время?
  time: 2